name: flutter_cached_video_android
description: flutter_cached_video_android is the Android implementation of the flutter_cached_video plugin, supporting video caching up to 512 MB. When the cache limit is exceeded, the oldest videos are removed. Built on ExoPlayer, it ensures smooth playback, reduces buffering, and improves offline video performance.
repository: https://github.com/Raghav117/flutter_cached_video_player/tree/master/video_player_android



version: 1.0.2

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.4.2

topics:
  - video
  - video-player
