name: flutter_cached_video
description: Enhanced video_player with Android caching, supports 512 MB, auto-clears old videos for smooth playback.
repository: https://github.com/Raghav117/flutter_cached_video_player
homepage: https://github.com/Raghav117/flutter_cached_video_player


version: 1.0.3

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_cached_video_android
      ios:
        default_package: video_player_avfoundation
      macos:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  
  flutter_cached_video_android: ^1.0.3
  html: ^0.15.0
  
  video_player_avfoundation: ^2.5.6
  video_player_platform_interface: ^6.2.0
  video_player_web: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any

topics:
  - video
  - video-player
