name: flutter_cached_video_player
description: An enhanced version of the video_player package that adds caching functionality for Android to improve video performance and offline access.
repository: https://github.com/Raghav117/flutter_cached_video_player
publish_to: none

version: 1.0.0

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_cached_video_player_android
      ios:
        default_package: flutter_cached_video_player_avfoundation
      macos:
        default_package: flutter_cached_video_player_avfoundation
      web:
        default_package: flutter_cached_video_player_web

dependencies:
  flutter:
    sdk: flutter
  
  flutter_cached_video_player_android: 
    path: ../video_player_android
  flutter_cached_video_player_avfoundation: 
    path: ../video_player_avfoundation
  flutter_cached_video_player_platform_interface:
    path: ../video_player_platform_interface
  flutter_cached_video_player_web:
    path: ../video_player_web

  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any

topics:
  - video
  - video-player
