name: flutter_cached_video_player_web
description: Web platform implementation of flutter_cached_video_player.
repository: https://github.com/Raghav117/flutter_cached_video_player
publish_to: none

version: 1.0.0

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      web:
        pluginClass: VideoPlayerPlugin
        fileName: video_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  
  flutter_cached_video_player_platform_interface:
    path: ../video_player_platform_interface

  flutter_web_plugins:
    sdk: flutter

  web: ">=0.5.1 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - video
  - video-player
